#SPDX-License-Identifier: MIT-0
---
# defaults file for software

docker:
  install: false
  add_users_to_docker_group: false

caddy:
  install: false
  domain: "training.ilifu.ac.za"
  email: "admin@training.ilifu.ac.za"
  acme_provider: "letsencrypt"
  port_http: 80
  port_https: 443

jupyterhub:
  install: false
  version: "5.4.2"
  admin_users:
    - ubuntu
  jupyter_user: jupyter
  jupyter_group: jupyter

  spawner_type: "slurm"

  spawner_config:
    partition: "debug"
    memory: "4G"
    cpus: 2
    time_limit: "01:00:00"
    prologue: ""
    epilogue: ""

  service:
    ip: "127.0.0.1"
    port: 8000
    allow_root: false

  authenticator: "pam"
  notebook_dir: "/home/{username}"
