- name: Install mariadb and configure
  vars:
    db_password: "{{ lookup('env', slurm.slurm_db_password_env_variable) }}"
  block:
    - name: Required packages
      apt:
        name:
          - software-properties-common
          - curl
          - ca-certificates
          - apt-transport-https
        state: latest
        update_cache: yes
      register: apt_res
      retries: 3
      delay: 15
      until: apt_res is success
    - name: Get MariaDB repo setup script
      get_url:
        url: https://r.mariadb.com/downloads/mariadb_repo_setup
        dest: /tmp/mariadb_repo_setup
        mode: "ugo+rx"
    - name: Run repo setup script
      command: "/tmp/mariadb_repo_setup"
    - name: Install MariaDB and related packages
      apt:
        name:
          - mariadb-server
          - libmariadb-dev
          - python3-pymysql
        state: latest
        update_cache: yes
      register: apt_res
      retries: 3
      delay: 15
      until: apt_res is success
    - name: Create mysql_config symbolic link
      file:
        src: /usr/bin/mariadb_config
        dest: /usr/bin/mysql_config
        owner: root
        group: root
        state: link
    - name: Configure MariaDB buffer pool size
      lineinfile:
        path: /etc/mysql/my.cnf
        regexp: '.*(innodb_buffer_pool_size *=).*'
        line: '\1 1024M'
        backrefs: yes
      notify: restart MariaDB service
    - name: Ensure Slurm DB present
      mysql_db:
        name: "{{ slurm.db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: yes

    - name: database password not defined
      debug:
        msg: "You need to define the environmental variable '{{ slurm.slurm_db_password_env_variable }}' for database configuration"
      when: db_password==''
    - name: Install and configure mariadb
      when: db_password != ''
      block:
        - name: Ensure Slurm DB user present
          mysql_user:
            name: "{{ slurm.db_user }}"
            password: "{{ slurm.db_password }}"
            priv: "{{ slurm_config.database.name }}.*:ALL"
            state: present
            login_unix_socket: /var/run/mysqld/mysqld.sock
          become: yes

    - name: Ensure slurmdbd configured
      block:
        - name: database password not defined
          debug:
            msg: "You need to define the environmental variable '{{ slurm.slurm_db_password_env_variable }}' for database configuration"
          when: db_password==''
        - name: configure slurmdbd
          when: db_password != ''
          block:
            - name: Ensure slurmdbd.conf present and configured
              template:
                src: slurmdbd.conf.template
                dest: /opt/slurm/{{ slurm_config.slurm_version }}/etc/slurmdbd.conf
                owner: slurm
                group: slurm
                mode: "u=rw,go="
      tags: "slurmdbd"

    - name: Copy systemd configure and enable systemd
      block:
        - name: Copy slurmdbd systemd file
          copy:
            src: "~{{ ansible_user }}/src/slurm/etc/slurmdbd.service"
            dest: /etc/systemd/system/
            remote_src: yes
            owner: root
            group: root
            mode: "u=rw,go=r"
          tags: "slurmdbd"
        - name: Reload daemon
          systemd:
            daemon_reload: yes
        - name: Enable slurmdbd service
          systemd:
            name: slurmdbd
            daemon_reload: yes
            enabled: yes
            state: restarted
          tags: "slurmdbd"

      tags: "systemd"
