#SPDX-License-Identifier: MIT-0
---
# Import handlers from Caddy role
- import_tasks: ../../caddy/handlers/main.yml

# handlers file for jupyterhub

- name: Restart JupyterHub
  become: yes
  systemd:
    name: jupyterhub
    state: restarted
    daemon_reload: yes

- name: Reload JupyterHub configuration
  become: yes
  systemd:
    name: jupyterhub
    state: restarted
