#SPDX-License-Identifier: MIT-0
---
# handlers file for caddy

- name: Reload systemd daemon
  become: yes
  systemd:
    daemon_reload: yes
  listen: "Reload systemd daemon"

- name: Validate Caddy configuration
  become: yes
  command: caddy validate --config /etc/caddy/Caddyfile
  listen: "Validate Caddy configuration"
  register: caddy_validation
  failed_when: caddy_validation.rc != 0

- name: Reload Caddy
  become: yes
  systemd:
    name: caddy
    state: reloaded
  listen: "Reload Caddy"

- name: Restart Caddy
  become: yes
  systemd:
    name: caddy
    state: restarted
  listen: "Restart Caddy"
