---
- hosts: base_image
  name: Install Galaxy and its requirements
  become: yes
  become_user: root
  tasks:
    - name: Install Galaxy Requirements
      retries: 3
      delay: 5
      apt:
        name: [
          'build-essential',
          'fail2ban',
          'git',
          'libbz2-dev',
          'libffi-dev',
          'liblzma-dev',
          'libncurses5-dev',
          'libreadline-dev',
          'libsqlite3-dev',
          'libssl-dev',
          'libxml2-dev',
          'libxmlsec1-dev',
          'llvm',
          'make',
          'python2.7',
          'python2.7-dev',
          'python-pip',
          'python-setuptools',
          'python-virtualenv',
          'tk-dev',
          'wget',
          'xz-utils',
          'zlib1g-dev',
          'zsh'
        ]
        state: latest
        update_cache: yes
