---
- name: Ensure StateSave dir exists and is owned by slurm
  file:
    path: /var/spool/slurm_state
    state: directory
    owner: slurm
    group: slurm
    mode: "ug=rwx,o="

- name: copy slurmctl systemd file
  copy:
    src: "~{{ ansible_user }}/src/slurm/etc/slurmctld.service"
    dest: /etc/systemd/system/
    remote_src: yes
    owner: root
    group: root
    mode: "u=rw,go=r"
  tags: "slurmctl"
- name: Reload daemon
  systemd:
    daemon_reload: yes
- name: Enable slurmctl service
  systemd:
    name: slurmctld
    daemon_reload: yes
    enabled: yes
    state: started
  tags: "slurmctl"

- name: Create cluster and initial account
  tags:
    - never
    - deploy_cluster
    - accounting
  become: yes
  #become_user: slurm
  block:
    - name: Create cluster
      command:
        argv:
          - /opt/slurm/{{ slurm.version }}/bin/sacctmgr
          - add
          - cluster
          - "{{ slurm_config.cluster_name }}"
      register: create_cluster_result
      failed_when: create_cluster_result.rc != 0 and "already exists" not in create_cluster_result.stdout
      changed_when: create_cluster_result.rc == 0
    - name: Add accounts
      command:
        argv:
          - /opt/slurm/{{ slurm.version }}/bin/sacctmgr
          - "--immediate"
          - add
          - account
          - "{{ item.key }}"
          - description="{{ item.value }}"
      register: add_accounts_result
      failed_when: add_accounts_result.rc != 0 and "Nothing new added" not in add_accounts_result.stdout
      changed_when: add_accounts_result.rc == 0
      with_dict:
        "{{ slurm.accounts }}"
      
#    - name: Add users to accounts
#      command:
#        argv:
#          - /opt/slurm/{{ slurm_version }}/bin/sacctmgr
#          - "--immediate"
#          - create
#          - user
#          - "{{ item.username }}"
#          - account="{{ item.account }}"
#          - adminlevel=None
#      with_items:
#        - "{{ users }}"
#      loop_control:
#        label: "{{ item.username }} [account: {{ item.account }}]"


        