- name: Ensure software directory exists
  when: software_directory.path != ""
  become: yes
  file:
    path: "{{ software_directory.path }}"
    owner: "{{ software_directory.owner }}"
    group: "{{ software_directory.group }}"
    mode: "{{ software_directory.mode }}"
    state: directory

- name: Install Valencia
  block:
    - name: Create Valencia directory
      become: yes
      file:
        path: "{{ software_directory.path }}/valencia"
        owner: "{{ software_directory.owner }}"
        group: "{{ software_directory.group }}"
        mode: "{{ software_directory.mode }}"
        state: directory
    - name: Clone valencia
      git:
        repo: https://github.com/ravel-lab/VALENCIA.git
        dest: "{{ software_directory.path }}/valencia"
      become: yes
      become_user: "{{ software_directory.owner }}"
    - name: Copy requirements.txt file for valencia
      copy:
        src: requirements.valencia
        dest: "/tmp/"
    - name: Create virtual environment for valencia
      pip:
        requirements: "/tmp/requirements.valencia"
        virtualenv: "{{ software_directory.path }}/valencia/.venv"
        virtualenv_python: python3
    - name: Patch Valencia python scripts to use venv python
      lineinfile:
        dest: "{{ software_directory.path }}/valencia/{{ item }}"
        regex: "^#!.*"
        line: "#!{{ software_directory.path }}/valencia/.venv/bin/python"
      loop:
        - Valencia.py
        - convert_qiime.py
    - name: Make convert_qiime.py executable
      file:
        path: "{{ software_directory.path }}/valencia/convert_qiime.py"
        mode: "ugo+x"


