---
# tasks file for roles/ldap_server

- name: Install Packages
  apt:
    name:
      - 'ldap-utils'
      - 'libldap2-dev'
      - 'libsasl2-dev'
      - 'libssl-dev'
      - 'python3-dev'
      - 'slapd'
      - 'virtualenv'
    state: latest
    update_cache: yes
  register: apt_res
  retries: 3
  delay: 15
  until: apt_res is success


# - name: Firewall rule -- allow port 389/LDAP traffic
#   iptables:
#     action: insert
#     chain: INPUT
#     destination_port: '389'
#     src_range: 192.168.101.100-192.168.101.255
#     jump: ACCEPT
#     protocol: tcp
#   tags:
#     - "iptables"  