---
# tasks file for roles/ldap_server
- name: Install Packages
  apt:
    name:
      - 'ldap-utils'
      - 'libldap2-dev'
      - 'libsasl2-dev'
      - 'libssl-dev'
      - 'python3-dev'
      - 'slapd'
      - 'virtualenv'
    state: latest
    update_cache: yes
  register: apt_res
  retries: 3
  delay: 15
  until: apt_res is success

- name: update debconf selections
  block:
    - name: Configure slapd organisation
      debconf:
        name: slapd
        question: shared/organization
        vtype: 'string'
        value: "{{ ldap_config.organisation }}"
      register: ldap_org
    - name: Configure slapd domain
      debconf:
        name: slapd
        question: slapd/domain
        vtype: 'string'
        value: "{{ ldap_config.ldap_dns_domain_name }}"
      register: ldap_domain

- name: Reconfigure slapd
  when: ldap_org.changed or ldap_domain.changed
  command: dpkg-reconfigure -f noninteractive slapd
  become: yes

- name: Copy ldap ssh key schema
  copy:
    src: openssh-lpk.ldif
    dest: /etc/ldap/schema/
  become: yes

- name: Add ssh key schema
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f openssh-lpk.ldif
  args:
    chdir: /etc/ldap/schema/
  become: yes
  register: add_sshkey_schema
  failed_when: add_sshkey_schema.rc != 0 and "Duplicate attributeType" not in add_sshkey_schema.stderr
  changed_when: add_sshkey_schema.rc == 0

- name: Set rootDN passwd
  tags: ldap_passwd
  vars:
    rootdn_passwd: "{{ lookup('env', ldap_config.password_env_variable) }}"
  when: rootdn_passwd != ''
  block:
    - name: get SSHA of ldap passwd
      command: slappasswd -s "{{ rootdn_passwd }}"
      register: slappasswd_output
    - name: Create changeroot ldif
      template:
        src: changerootpw.ldif
        dest: /tmp/
    - name: Update rootDN ldap password
      command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /tmp/changerootpw.ldif
      become: yes



# - name: Firewall rule -- allow port 389/LDAP traffic
#   iptables:
#     action: insert
#     chain: INPUT
#     destination_port: '389'
#     src_range: 192.168.101.100-192.168.101.255
#     jump: ACCEPT
#     protocol: tcp
#   tags:
#     - "iptables"  