- name: Add nextflow to /etc/skel
  block:
    - name: Make sure skel bin dir exists
      file:
        path: "/etc/skel/bin"
        owner: root
        group: root
        mode: "u+rwx,go+rx"
        recurse: yes
        state: directory
    - name: Download NextFlow
      get_url:
        url: https://get.nextflow.io
        dest: "/etc/skel/bin/nextflow"
        mode: "ugo=rx"
        owner: root
        group: root
    - name: Setup the rest of nextflow
      block:
        - name: Run nextflow for the first time
          command: "/etc/skel/bin/nextflow"
          args:
            chdir: "/etc/skel"
            creates: "/root/.nextflow"
          become: yes
        - name: Copy .nextflow to skel
          copy:
            src: /root/.nextflow
            dest: /etc/skel
            remote_src: yes
  run_once: yes
