- name: Add nextflow to /etc/skel
  block:
    - name: Make sure skel bin dir exists
      file:
        path: "/etc/skel/bin"
        owner: root
        group: root
        mode: "u+rwx,go+rx"
        recurse: yes
        state: directory
    - name: Download NextFlow
      get_url:
        url: https://get.nextflow.io
        dest: "/etc/skel/bin/nextflow"
        mode: "ugo=rx"
        owner: root
        group: root
#    - name: Ensure each user has a bin directory
#      file:
#        path: "{{ home_dir }}/{{ item.username }}/bin"
#        owner: "{{ item.username }}"
#        group: "{{ item.username }}"
#        mode: "ug=rwx,o="
#        state: directory
#      with_items:
#        - "{{ users }}"
#    - name: Copy nextflow.bash to user's bin dir
#      copy:
#        src: "{{ software_dir }}/src/nextflow.bash"
#        dest: "{{ home_dir }}/{{ item.username }}/bin/nextflow"
#        remote_src: yes
#        owner: "{{ item.username }}"
#        group: "{{ item.username }}"
#        mode: "ug=rx,o="
#      with_items:
#        - "{{ users }}"

#    - name: Install NextFlow in users' homes
#      command: "{{ home_dir }}/{{ item.username }}/bin/nextflow"
#      args:
#        chdir: "{{ home_dir }}/{{ item.username }}"
#        creates: "{{ home_dir }}/{{ item.username }}/.nextflow"
#      become: yes
#      become_user: "{{ item.username }}"
#      with_items:
#        - "{{ users }}"
#      loop_control:
#        label: "{{ item.username }}"
  run_once: yes
