- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: ".*\\s{{ item }}"
    line: "{{ hostvars[item].private_ip }}    {{ item }}"
    state: present
  with_items: "{{ groups['all'] }}"

- name: Set hostname
  hostname:
      name: "{{ inventory_hostname }}"
  become: yes




# user:
#     name: "{{ item.username }}"
#     state: present
#     uid: "{{ item.uid }}"
#     group: slurm_user
#     groups: "{{ item.username }}"
#     home: "/cbio/home/{{ item.username }}"
#     skeleton: /etc/skel
#     generate_ssh_key: yes
#     ssh_key_type: ed25519
#     shell: /bin/bash