- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: ".*\\s{{ item }}"
    line: "{{ hostvars[item].private_ip }}    {{ item }}"
    state: present
  with_items: "{{ groups['all'] }}"

- name: Set hostname
  hostname:
      name: "{{ inventory_hostname }}"
  become: yes

