---
- hosts: slurm
  roles:
    - slurm_common

- hosts: slurm_headnode
  roles:
    - slurm_common
    - slurm_headnode
    - nextflow
    - software
  tags:
    - slurm

- hosts: slurm_database
  roles:
    - slurm_common
    - db_server
  tags:
    - slurm
    - database

- hosts: slurm_controller
  roles:
    - slurm_common
    - slurm_controller
  tags:
    - slurm
    - controller

- hosts: slurm_worker
  roles:
    - slurm_common
    - slurm_worker
#    - nextflow
  tags:
    - slurm
    
