---
- hosts: slurm
  roles:
    - slurm_common
#    - hosts

- hosts: slurm_headnode
  roles:
    - ceph
    - slurm_headnode
#    - nextflow
    - software
  tags:
    - slurm

- hosts: slurm_database
  roles:
    - db_server
  tags:
    - slurm
    - database

- hosts: slurm_controller
  roles:
    - slurm_controller
  tags:
    - slurm
    - controller

- hosts: slurm_compute
  roles:
    - ceph
    - slurm_worker
#    - nextflow
  tags:
    - slurm

