---
- hosts: slurm
  roles:
    - slurm_common
    - hosts
    - manage_users

- hosts: slurm_headnode
  roles:
    - slurm_headnode
  tags:
    - slurm

- hosts: slurm_database
  roles:
    - db_server
  tags:
    - slurm
    - database

- hosts: slurm_controller
  roles:
    - slurm_controller
    - db_server
  tags:
    - slurm

- hosts: slurm_worker
  roles:
    - slurm_worker
    - nextflow
  tags:
    - slurm
    
